--- #YAML:1.0
name:                AnyEvent-Twitter
version:             0.1
abstract:            Implementation of the Twitter API for AnyEvent
license:             perl
author:              
    - Robin Redeker <elmex@x-paste.de>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    AnyEvent:                      3.5
    AnyEvent::HTTP:                0
    JSON:                          0
    MIME::Base64:                  0
    Object::Event:                 0
    Scalar::Util:                  0
    Test::More:                    0
    URI::URL:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
