#!/opt/perl/bin/perl
use AnyEvent;
use AnyEvent::Twitter;

my $twitty =
   AnyEvent::Twitter->new (
      username => $ARGV[0],
      password => $ARGV[1],
      bandwidth => 0.6,
   );

$twitty->reg_cb (
   error => sub {
      my ($twitty, $error) = @_;

      warn "Error: $error\n";
   },
   statuses_friends => sub {
      my ($twitty, @statuses) = @_;

      for (@statuses) {
         my ($pp_status, $raw_status) = @$_;
         printf "new friend status: %s: %s\n",
               $pp_status->{screen_name},
               $pp_status->{text};
      }
   },
   next_request_in => sub {
      my ($twitty, $secs) = @_;

      print "Next request in: $secs seconds!\n";
   }
);

$twitty->receive_statuses_friends; # start polling for friend statuses

$twitty->start;

AnyEvent->condvar->recv;
